use UNIVER;

Select GROUPS.FACULTY, PULPIT.PULPIT, GROUPS.PROFESSION, SUBJECT.SUBJECT, STUDENT.NAME,
Case
when(PROGRESS.NOTE=6)then 'six'
when(PROGRESS.NOTE=7)then 'seven'
when(PROGRESS.NOTE=8)then 'eight'
else 'error'
end [Note]
FROM PROGRESS 
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
INNER JOIN PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
Where PROGRESS.NOTE between 6 and 8
ORDER BY PROGRESS.NOTE DESC