use UNIVER;

Select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
From AUDITORIUM inner join AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE And
AUDITORIUM_TYPE.AUDITORIUM_TYPENAME Like '%computer%' 