use UNIVER

Select PULPIT.PULPIT_NAME
from PULPIT, FACULTY
where FACULTY.FACULTY = PULPIT.FACULTY
and FACULTY.FACULTY In (Select PROFESSION.FACULTY 
from PROFESSION 
Where PROFESSION.PROFESSION_NAME like '%technologies%')