use UNIVER

Select AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
From AUDITORIUM au1
Where AUDITORIUM_CAPACITY = (Select top(1) AUDITORIUM_CAPACITY
From AUDITORIUM au2
Where au2.AUDITORIUM_TYPE = au1.AUDITORIUM_TYPE
Order by AUDITORIUM_CAPACITY desc)