use UNIVER

Select AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
From AUDITORIUM 
Where AUDITORIUM_CAPACITY >= ALL(Select AUDITORIUM_CAPACITY 
--From AUDITORIUM WHERE AUDITORIUM_TYPE like 'LK')
From AUDITORIUM WHERE AUDITORIUM_TYPE like 'LK-K')
