use UNIVER

Select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, ROUND(AVG(CAST(PROGRESS.NOTE as float(4))), 2)[NOTE]
From FACULTY inner join GROUPS
ON FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT
On GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS
On STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
Where FACULTY.FACULTY = 'TOB'
--GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
GROUP BY ROLLUP (GROUPS.PROFESSION, PROGRESS.SUBJECT), FACULTY.FACULTY

