use UNIVER

Select AUDITORIUM.AUDITORIUM_TYPE,
max(AUDITORIUM.AUDITORIUM_CAPACITY)[Max_size],
min(AUDITORIUM.AUDITORIUM_CAPACITY)[Min_size],
avg(AUDITORIUM.AUDITORIUM_CAPACITY)[average_size],
count(AUDITORIUM.AUDITORIUM_TYPE)[number_of_auditorium],
sum(AUDITORIUM.AUDITORIUM_CAPACITY)[summa]
From AUDITORIUM inner join AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
Group by AUDITORIUM.AUDITORIUM_TYPE