use UNIVER

Select FACULTY, SUBJECT,
AVG(PROGRESS.NOTE)[grade]
From PROGRESS inner join STUDENT 
On PROGRESS.IDSTUDENT = PROGRESS.IDSTUDENT inner join GROUPS
On GROUPS.IDGROUP = STUDENT.IDGROUP 
Where GROUPS.FACULTY = 'TOB'
Group by FACULTY, SUBJECT
